name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  quality:
    name: Lint, Test, Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Format check (gofmt)
        run: |
          out=$(gofmt -s -l .)
          if [ -n "$out" ]; then
            echo "Unformatted files:" >&2
            echo "$out" >&2
            exit 1
          fi

      - name: Vet
        run: go vet ./...

      - name: Static check
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          "$(go env GOPATH)/bin/staticcheck" ./...

      - name: Test (race)
        run: go test -v -race ./...

      - name: Build
        run: go build ./...

  docker:
    name: Docker build
    runs-on: ubuntu-latest
    needs: quality
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build image
        run: docker build -t bitcoin-ltp:ci .

